spring:
    profiles:
        active: live
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: nikos8516
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
            WRITE_DATES_AS_TIMESTAMPS: false
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

application:
    database-schema: feely
    time-zone: Europe/Athens
    indico:
        apiKey: d93a3ddfda516d9e8427e6a3530f6ad2
        
    elasticsearch:
        host: localhost
        port: 9300
        cluster-name: elasticsearch
        user-index: user_idx
        diary-index: diary_idx
        document-type: entry
        number-of-replicas: 1
        number-of-shards: 5
        cluster-sniff: false