spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: nikos8516
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
            WRITE_DATES_AS_TIMESTAMPS: false
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

    application:
        database-schema: feely
        time-zone: Europe/Athens
        elasticsearch:
            host: localhost
            port: 9200
            cluster-name: feely
            index:user_idx
            document-type: user