CREATE TABLE FEELING
(
	ID SERIAL NOT NULL,
	NAME VARCHAR(255),
	TIMBRE VARCHAR(255),
	POTENCY INTEGER NOT NULL,
	CONSTRAINT FEELING_PK PRIMARY KEY ( ID )
);

ALTER TABLE FEELING ADD CONSTRAINT FEELINGS_U01 UNIQUE ( NAME );

CREATE TABLE FEELER
(
	ID SERIAL NOT NULL,
	NAME VARCHAR,
	SURNAME VARCHAR,
	EMAIL VARCHAR,
	GENDER VARCHAR,
	AGE INTEGER,
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	LAST_FELT  VARCHAR(255) NULL,
	TIMES_EXPRESSED VARCHAR(255),
	CONSTRAINT FEELER_PK PRIMARY KEY ( ID )
);

ALTER TABLE FEELER ADD CONSTRAINT FEELER_U01 UNIQUE ( USERNAME );

--ALTER TABLE FEELER ADD CONSTRAINT FEELER_FK01 FOREIGN KEY ( LAST_FELT ) REFERENCES FEELING ( NAME );